# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Myjoy.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frm(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1003, 849)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-10, 0, 1021, 851))
        self.label.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 1001, 841))
        self.label_2.setStyleSheet("background-image: url(./resources/8.jpg);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(920, 0, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton#pushButton_5 {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 139, 255), stop:1 rgba(70, 130, 180, 255)); /* Dark blue gradient */\n"
"    color: rgba(255, 255, 255, 255); /* White text for contrast */\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#pushButton_5:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(25, 25, 112, 255), stop:1 rgba(100, 149, 237, 255)); /* Lighter blue gradient for hover */\n"
"}\n"
"\n"
"QPushButton#pushButton_5:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(0, 0, 128, 255); /* Solid navy blue for pressed state */\n"
"}\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(840, 0, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton#pushButton_6 {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 139, 255), stop:1 rgba(70, 130, 180, 255)); /* Dark blue gradient */\n"
"    color: rgba(255, 255, 255, 255); /* White text for contrast */\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#pushButton_6:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(25, 25, 112, 255), stop:1 rgba(100, 149, 237, 255)); /* Lighter blue gradient for hover */\n"
"}\n"
"\n"
"QPushButton#pushButton_6:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(0, 0, 128, 255); /* Solid navy blue for pressed state */\n"
"}\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(450, 800, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton#pushButton_7 {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 139, 255), stop:1 rgba(70, 130, 180, 255)); /* Dark blue gradient */\n"
"    color: rgba(255, 255, 255, 255); /* White text for contrast */\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#pushButton_7:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(25, 25, 112, 255), stop:1 rgba(100, 149, 237, 255)); /* Lighter blue gradient for hover */\n"
"}\n"
"\n"
"QPushButton#pushButton_7:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(0, 0, 128, 255); /* Solid navy blue for pressed state */\n"
"}\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton#pushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 139, 255), stop:1 rgba(70, 130, 180, 255)); /* Dark blue gradient */\n"
"    color: rgba(255, 255, 255, 255); /* White text for contrast */\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#pushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(25, 25, 112, 255), stop:1 rgba(100, 149, 237, 255)); /* Lighter blue gradient for hover */\n"
"}\n"
"\n"
"QPushButton#pushButton:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(0, 0, 128, 255); /* Solid navy blue for pressed state */\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(280, 40, 411, 61))
        font = QtGui.QFont()
        font.setFamily("Colonna MT")
        font.setPointSize(52)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("\n"
"color: rgb(0, 0, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 190, 411, 61))
        font = QtGui.QFont()
        font.setFamily("Colonna MT")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("\n"
"color: rgb(0, 0, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(20, 450, 411, 61))
        font = QtGui.QFont()
        font.setFamily("Colonna MT")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("\n"
"color: rgb(0, 0, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(20, 240, 55, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(30, 500, 55, 16))
        self.label_7.setObjectName("label_7")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(640, 210, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton#pushButton_8 {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 139, 255), stop:1 rgba(70, 130, 180, 255)); /* Dark blue gradient */\n"
"    color: rgba(255, 255, 255, 255); /* White text for contrast */\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#pushButton_8:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(25, 25, 112, 255), stop:1 rgba(100, 149, 237, 255)); /* Lighter blue gradient for hover */\n"
"}\n"
"\n"
"QPushButton#pushButton_8:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(0, 0, 128, 255); /* Solid navy blue for pressed state */\n"
"}\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(640, 250, 341, 271))
        self.label_9.setStyleSheet("background-image: url(./resources/1.png);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(760, 0, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton#pushButton_9 {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 139, 255), stop:1 rgba(70, 130, 180, 255)); /* Dark blue gradient */\n"
"    color: rgba(255, 255, 255, 255); /* White text for contrast */\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#pushButton_9:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(25, 25, 112, 255), stop:1 rgba(100, 149, 237, 255)); /* Lighter blue gradient for hover */\n"
"}\n"
"\n"
"QPushButton#pushButton_9:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(0, 0, 128, 255); /* Solid navy blue for pressed state */\n"
"}\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "TextLabel"))
        self.pushButton_5.setText(_translate("Form", "Contact Us"))
        self.pushButton_6.setText(_translate("Form", "About Us"))
        self.pushButton_7.setText(_translate("Form", "Home"))
        self.pushButton.setText(_translate("Form", "SWAY AWAY "))
        self.label_3.setText(_translate("Form", "JOYLAND"))
        self.label_4.setText(_translate("Form", "RATINGS"))
        self.label_5.setText(_translate("Form", "REVIEWS"))
        self.label_6.setText(_translate("Form", "TextLabel"))
        self.label_7.setText(_translate("Form", "TextLabel"))
        self.pushButton_8.setText(_translate("Form", "Directions"))
        self.pushButton_9.setText(_translate("Form", "Home"))
import pics


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Frm()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
